on:
    push:
        branches:
            - master

jobs:
    create-deployment-artifacts:
        name: Create deployment artifacts
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Compile CSS & JS
              run: |
                npm install
                npm run build
                

              